//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Resources.ServicesTexts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServicesTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServicesTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealEstate.Resources.ServicesTexts.ServicesTexts", typeof(ServicesTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building design.
        /// </summary>
        public static string BuildingDesign {
            get {
                return ResourceManager.GetString("BuildingDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction of fences.
        /// </summary>
        public static string ConstructionOfFences {
            get {
                return ResourceManager.GetString("ConstructionOfFences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration works.
        /// </summary>
        public static string DecorationWorks {
            get {
                return ResourceManager.GetString("DecorationWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering networks.
        /// </summary>
        public static string EngineeringNetworks {
            get {
                return ResourceManager.GetString("EngineeringNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facade decoration.
        /// </summary>
        public static string FacadeDecoration {
            get {
                return ResourceManager.GetString("FacadeDecoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General construction works.
        /// </summary>
        public static string GeneralConstructionWorks {
            get {
                return ResourceManager.GetString("GeneralConstructionWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of facades.
        /// </summary>
        public static string InstallationOfFacades {
            get {
                return ResourceManager.GetString("InstallationOfFacades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of foundation.
        /// </summary>
        public static string InstallationOfFoundation {
            get {
                return ResourceManager.GetString("InstallationOfFoundation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of roof structures.
        /// </summary>
        public static string InstallationOfRoofStructures {
            get {
                return ResourceManager.GetString("InstallationOfRoofStructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interior painting.
        /// </summary>
        public static string InteriorPainting {
            get {
                return ResourceManager.GetString("InteriorPainting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscaping.
        /// </summary>
        public static string Landscaping {
            get {
                return ResourceManager.GetString("Landscaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor utility.
        /// </summary>
        public static string OutdoorUtility {
            get {
                return ResourceManager.GetString("OutdoorUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastering.
        /// </summary>
        public static string Plastering {
            get {
                return ResourceManager.GetString("Plastering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services we provide:.
        /// </summary>
        public static string ServicesWeProvide {
            get {
                return ResourceManager.GetString("ServicesWeProvide", resourceCulture);
            }
        }
    }
}
