// <auto-generated />
namespace RealEstate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingPictures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingPictures));
        
        string IMigrationMetadata.Id
        {
            get { return "201704241739154_AddingPictures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
